FROM oven/bun:1.3.12

WORKDIR /app

COPY . .

RUN bun install --frozen-lockfile

ENV NODE_ENV=production

RUN bun run turbo -F server build

WORKDIR /app/apps/server

ENV PORT=3001

EXPOSE 3001

CMD ["bun", "dist/index.mjs"]
