import type { UserRow } from "@/components/dashboard/admin/users-columns";

export const MOCK_USERS: UserRow[] = [
  {
    id: "u_01",
    name: "cheluchukwu okonkwo",
    email: "okonkwoc1680@student.babcock.edu.com",
    image: null,
    role: "public_student",
    emailVerified: false,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-28T10:14:00Z"),
  },
  {
    id: "u_02",
    name: "cheluchukwu okonkwo",
    email: "okonkwoc1680@babcock.edu.com",
    image: null,
    role: "public_student",
    emailVerified: false,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-28T10:20:00Z"),
  },
  {
    id: "u_03",
    name: "Soludo Imah",
    email: "imahs0470@student.babcock.edu.ng",
    image: null,
    role: "public_student",
    emailVerified: true,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-28T11:02:00Z"),
  },
  {
    id: "u_04",
    name: "akan essien",
    email: "andrew-essiena1366@student.babcock.edu.ng",
    image: null,
    role: "public_student",
    emailVerified: true,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-28T11:30:00Z"),
  },
  {
    id: "u_05",
    name: "David Ojodu",
    email: "ojodud2575@student.babcock.edu.ng",
    image: null,
    role: "public_student",
    emailVerified: false,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-28T12:05:00Z"),
  },
  {
    id: "u_06",
    name: "Usen Victor",
    email: "usenv1129@student.babcock.edu.ng",
    image: null,
    role: "public_student",
    emailVerified: false,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-28T12:40:00Z"),
  },
  {
    id: "u_07",
    name: "Mei Tanaka",
    email: "mei.tanaka@sycom.test",
    image: null,
    role: "content_creator",
    emailVerified: true,
    banned: false,
    organizations: ["Babcock CS"],
    createdAt: new Date("2026-03-12T09:14:00Z"),
  },
  {
    id: "u_08",
    name: "Lucas Pereira",
    email: "lucas.p@sycom.test",
    image: null,
    role: "content_creator",
    emailVerified: true,
    banned: false,
    organizations: ["Babcock CS", "Lagos Devs"],
    createdAt: new Date("2026-03-15T10:00:00Z"),
  },
  {
    id: "u_09",
    name: "Priya Raman",
    email: "priya.r@sycom.test",
    image: null,
    role: "platform_admin",
    emailVerified: true,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-02-14T14:00:00Z"),
  },
  {
    id: "u_10",
    name: "Henri Dubois",
    email: "henri@sycom.test",
    image: null,
    role: "public_student",
    emailVerified: true,
    banned: true,
    organizations: [],
    createdAt: new Date("2025-11-20T09:18:00Z"),
  },
  {
    id: "u_11",
    name: "Abraham Adeke",
    email: "abraham@sycom.test",
    image: null,
    role: "platform_admin",
    emailVerified: true,
    banned: false,
    organizations: ["Sycom Core"],
    createdAt: new Date("2025-09-12T10:14:00Z"),
  },
  {
    id: "u_12",
    name: "Yusuf Demir",
    email: "yusuf.d@sycom.test",
    image: null,
    role: null,
    emailVerified: false,
    banned: false,
    organizations: [],
    createdAt: new Date("2026-04-15T18:40:00Z"),
  },
];
