-- AUTO-GENERATED by scripts/cloudinary-audit.ts — review before running.
-- Removes storage rows whose Cloudinary asset is being deleted (bucket B).
-- Run against EACH database that had these rows (prod, and dev if applicable).
DELETE FROM storage WHERE public_id IN (
  'sycom-lms/course_thumbnails/crs_695f5c67-7f12-4e83-b048-683d50b539a3/4e0508ad-739e-470f-b1a3-fb6d5bae3439',
  'sycom-lms/course_thumbnails/crs_ac83bf69-d4a6-4058-a421-6adc29ee2400/30ac4aa1-f732-41ed-b31b-4d021f852285',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/045afe62-9fa1-436a-8d18-73a173250dbb',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/4e984599-8ee4-45ed-9742-2c37ee083df8',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/7b2ce51b-332c-43c7-bb1c-660f383299c0',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/b4f56fcb-5f84-4051-9d7e-1177e8e2762a',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/dc30309b-9eab-46ab-8b0a-3c8eb05a84c7',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/e91d69ae-784e-4121-9fd5-289e3735f163',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/f4189caf-96fd-4725-9048-78e29ce87535',
  'sycom-lms/lesson_artifacts/lsn_ef2a681a-ea59-46bd-bc26-a2dff091ffab/5372c9dc-2963-4490-a8d3-1f7eb8855242',
  'sycom-lms/lesson_artifacts/lsn_ef2a681a-ea59-46bd-bc26-a2dff091ffab/57852005-2b39-4d32-bfd7-16253f3c6716',
  'sycom-lms/lesson_artifacts/lsn_f3341f5a-d326-411e-b40a-38b97f7fc127/d9076e40-82d8-420c-a75d-a393d4f6e9d0',
  'sycom-lms/organization_logos/6125c6fb-63af-4201-82bb-90f1186b0f8d/3ba4db1a-2eaa-48ea-8c07-0af1a5021269',
  'sycom-lms/organization_logos/6942a63d-4d68-4dd5-af1d-e49f95a9b63e/ce71b64e-c228-4d04-9245-d8268b512a62',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/1b7156d9-5ed1-41e0-b043-ba5b6a8d243a.xlsx',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/5bed0eb0-4951-4a47-b618-1095fd9aef51.xlsx',
  'sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/69c2a0e6-1539-4b47-b6da-7ed51839c3a8.csv',
  'sycom-lms/lesson_artifacts/lsn_f3341f5a-d326-411e-b40a-38b97f7fc127/269f3fd2-40fb-441d-9f62-3edd973b5755.xlsx'
);
