#!/usr/bin/env bash
# AUTO-GENERATED by scripts/cloudinary-audit.ts — review before running.
# Deletes: unreferenced orphans (no storage row, no content reference).
# Credentials are read from apps/server/.env; nothing is hardcoded here.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
set -a; source "$ROOT/apps/server/.env"; set +a
CLOUD="$CLOUDINARY_CLOUD_NAME"; KEY="$CLOUDINARY_API_KEY"; SECRET="$CLOUDINARY_API_SECRET"

echo "Deleting 1 image asset(s)…"
curl -s -u "$KEY:$SECRET" -X DELETE \
  "https://api.cloudinary.com/v1_1/$CLOUD/resources/image/upload" \
  --data-urlencode 'invalidate=true' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_test_sig/c2d56de5-0be5-4fdc-b2c1-b8146fe40eb6' \
  ; echo

echo "Deleting 1 raw asset(s)…"
curl -s -u "$KEY:$SECRET" -X DELETE \
  "https://api.cloudinary.com/v1_1/$CLOUD/resources/raw/upload" \
  --data-urlencode 'invalidate=true' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_85825943-ee52-4530-a3e3-ec626dbe264a/3988444b-279c-4d38-89e4-af55e71635c7.xlsx' \
  ; echo

echo "Done."
