#!/usr/bin/env bash
# AUTO-GENERATED by scripts/cloudinary-audit.ts — review before running.
# Deletes: stale assets — has storage row but not referenced by any content.
# Credentials are read from apps/server/.env; nothing is hardcoded here.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
set -a; source "$ROOT/apps/server/.env"; set +a
CLOUD="$CLOUDINARY_CLOUD_NAME"; KEY="$CLOUDINARY_API_KEY"; SECRET="$CLOUDINARY_API_SECRET"

echo "Deleting 17 image asset(s)…"
curl -s -u "$KEY:$SECRET" -X DELETE \
  "https://api.cloudinary.com/v1_1/$CLOUD/resources/image/upload" \
  --data-urlencode 'invalidate=true' \
  --data-urlencode 'public_ids[]=sycom-lms/course_thumbnails/crs_695f5c67-7f12-4e83-b048-683d50b539a3/4e0508ad-739e-470f-b1a3-fb6d5bae3439' \
  --data-urlencode 'public_ids[]=sycom-lms/course_thumbnails/crs_ac83bf69-d4a6-4058-a421-6adc29ee2400/30ac4aa1-f732-41ed-b31b-4d021f852285' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/045afe62-9fa1-436a-8d18-73a173250dbb' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/4e984599-8ee4-45ed-9742-2c37ee083df8' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/718a106c-4907-42fb-83b2-2cc5ca20e9e5' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/7b2ce51b-332c-43c7-bb1c-660f383299c0' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/b43aada2-597e-438d-8586-86c1cc495ab1' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/b4f56fcb-5f84-4051-9d7e-1177e8e2762a' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/dc30309b-9eab-46ab-8b0a-3c8eb05a84c7' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/e91d69ae-784e-4121-9fd5-289e3735f163' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/eac462be-39b0-4f34-a89d-9ef79cf933c8' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/f4189caf-96fd-4725-9048-78e29ce87535' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_ef2a681a-ea59-46bd-bc26-a2dff091ffab/5372c9dc-2963-4490-a8d3-1f7eb8855242' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_ef2a681a-ea59-46bd-bc26-a2dff091ffab/57852005-2b39-4d32-bfd7-16253f3c6716' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_f3341f5a-d326-411e-b40a-38b97f7fc127/d9076e40-82d8-420c-a75d-a393d4f6e9d0' \
  --data-urlencode 'public_ids[]=sycom-lms/organization_logos/6125c6fb-63af-4201-82bb-90f1186b0f8d/3ba4db1a-2eaa-48ea-8c07-0af1a5021269' \
  --data-urlencode 'public_ids[]=sycom-lms/organization_logos/6942a63d-4d68-4dd5-af1d-e49f95a9b63e/ce71b64e-c228-4d04-9245-d8268b512a62' \
  ; echo

echo "Deleting 4 raw asset(s)…"
curl -s -u "$KEY:$SECRET" -X DELETE \
  "https://api.cloudinary.com/v1_1/$CLOUD/resources/raw/upload" \
  --data-urlencode 'invalidate=true' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/1b7156d9-5ed1-41e0-b043-ba5b6a8d243a.xlsx' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/5bed0eb0-4951-4a47-b618-1095fd9aef51.xlsx' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_0fc4e6d0-353b-4c13-aa6a-715cde2fd63f/69c2a0e6-1539-4b47-b6da-7ed51839c3a8.csv' \
  --data-urlencode 'public_ids[]=sycom-lms/lesson_artifacts/lsn_f3341f5a-d326-411e-b40a-38b97f7fc127/269f3fd2-40fb-441d-9f62-3edd973b5755.xlsx' \
  ; echo

echo "Done."
