name: Trigger auto deployment for sycomlearn-prod-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/sycomlearn-prod-app-AutoDeployTrigger-a8a7be45-b2b6-4b24-8511-1642f830ad34.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SYCOMLEARNPRODAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SYCOMLEARNPRODAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SYCOMLEARNPRODAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sycomlearnprodacr01.azurecr.io
          registryUsername: ${{ secrets.SYCOMLEARNPRODAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SYCOMLEARNPRODAPP_REGISTRY_PASSWORD }}
          containerAppName: sycomlearn-prod-app
          resourceGroup: sycomlearn-prod-rg
          imageToBuild: sycomlearnprodacr01.azurecr.io/sycomlearn-prod-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


